version: '3.8'

services:
  mysql:
    image: mysql:latest
    volumes:
      - data:/var/lib/mysql
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    networks:
      - backend

  node:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./wait-for.sh mysql:3306 -- yarn start
    env_file: .env
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules/
      - ./sequelize/config/:/home/node/app/config/config.js

  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - web-root:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
    networks:
      - backend

volumes:
  data:
    driver: local
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /Users/valerojasm/Desktop/IMFD/PanelAppGraph
      o: bind

networks:
  backend:
